import { Inter, Hind_Madurai, Poppins } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Providers } from "@/store/Providers";
import SessionProvide from "@/services/SessionProvide";
import { SocketProvider } from "@/contexts/socket";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], variable: '--font-poppins' })
const hindMadurai = Hind_Madurai({ subsets: ["latin"], weight: ['300', '400', '500', '600', '700',], variable: '--font-hind_madurai' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SocketProvider>
      <SessionProvide>
        <html lang="en">
          <body className={`${inter.className} ${hindMadurai.variable} ${poppins.variable} font-poppins relative`}>
            <Providers>
              <Suspense>
                {children}
              </Suspense>
            </Providers>
          </body>
        </html>
      </SessionProvide>
    </SocketProvider>
  );
}
